# permissions for end users to edit psqlrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psqlrestore-editor-role
rules:
- apiGroups:
  - astrolabe.io
  resources:
  - psqlrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - astrolabe.io
  resources:
  - psqlrestores/status
  verbs:
  - get
