# permissions for end users to edit psqlsnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psqlsnapshot-editor-role
rules:
- apiGroups:
  - astrolabe.io
  resources:
  - psqlsnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - astrolabe.io
  resources:
  - psqlsnapshots/status
  verbs:
  - get
