# permissions for end users to view psqlsnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psqlsnapshot-viewer-role
rules:
- apiGroups:
  - astrolabe.io
  resources:
  - psqlsnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - astrolabe.io
  resources:
  - psqlsnapshots/status
  verbs:
  - get
