
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - astrolabe.io
  resources:
  - filesystemsnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - astrolabe.io
  resources:
  - filesystemsnapshots/finalizers
  verbs:
  - update
- apiGroups:
  - astrolabe.io
  resources:
  - filesystemsnapshots/status
  verbs:
  - get
  - patch
  - update
