---
apiVersion: v1
kind: Service
metadata:
  name: astrolabe
spec:
  type: NodePort
  ports:
    - name: astrolabe-port
      port: 1323
      protocol: TCP
      nodePort: 31323
    - name: astrolabe-minio-http
      port: 9000
      protocol: TCP
      nodePort: 30900
  selector:
    app: astrolabe-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: astrolabe-repo
spec:
  storageClassName: astrolabe-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fs-root
spec:
  storageClassName: astrolabe-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: astrolabe-server
  name: astrolabe-server
spec:
  containers:
  - name: astrolabe-server
    image: zubron/astrolabe_server:demo
    volumeMounts:
    - name: astrolabe-pes
      mountPath: /etc/astrolabe_conf/pes
    - name: astrolabe-conf
      mountPath: /etc/astrolabe_conf
    - name: astrolabe-repo
      mountPath: /astrolabe-repo
    - name: fs-root
      mountPath: /fs_root
    ports:
    - containerPort: 1323
      name: client
      protocol: TCP
  - name: astrolabe-controller
    image: zubron/astrolabe-controller:demo
    volumeMounts:
    - name: astrolabe-pes
      mountPath: /etc/astrolabe_conf/pes
    - name: astrolabe-conf
      mountPath: /etc/astrolabe_conf
    - name: astrolabe-repo
      mountPath: /astrolabe-repo
    - name: fs-root
      mountPath: /fs_root
    ports:
    - containerPort: 2345
      name: delve
      protocol: TCP
  - name: astrolabe-minio
    image: zubron/astrolabe_minio:demo
    volumeMounts:
    - name: astrolabe-pes
      mountPath: /etc/astrolabe_conf/pes
    - name: astrolabe-conf
      mountPath: /etc/astrolabe_conf
    - name: astrolabe-repo
      mountPath: /astrolabe-repo
    - name: fs-root
      mountPath: /fs_root
    ports:
    - containerPort: 9000
      name: minio
      protocol: TCP
  volumes:
    - name: astrolabe-pes
      configMap:
        name: astrolabe-pes
    - name: astrolabe-conf
      configMap:
        name: astrolabe-conf
    - name: astrolabe-repo
      persistentVolumeClaim:
        claimName: astrolabe-repo
    - name: fs-root
      persistentVolumeClaim:
        claimName: fs-root
  imagePullSecrets:
  - name: regcred
  serviceAccountName: astrolabe-service-account
  restartPolicy: Always
