---
apiVersion: v1
kind: Service
metadata:
  name: astrolabe
spec:
  type: NodePort
  ports:
    - name: astrolabe-port
      port: 1323
      protocol: TCP
      targetPort: 1323
  selector:
    app: astrolabe-server
    #  - name: astrolabe-minio-http
    #    port: 9000
    #    protocol: TCP
    #    targetPort: 9000
    #  selector:
    #    app: astrolabe-minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: astrolabe-repo
spec:
  storageClassName: astrolabe-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: astrolabe-server
  name: astrolabe-server
spec:
#  volumes:
#    - name: etcd0-storage
#      persistentVolumeClaim:
#       claimName: etcd0-pv-claim
#  name: astrolabe-server
  containers:
  - name: astrolabe-server
    image: dsmithuchida/astrolabe_server:06-08-2020-001
    volumeMounts:
    - name: astrolabe-pes
      mountPath: /etc/astrolabe_conf/pes
    - name: astrolabe-conf
      mountPath: /etc/astrolabe_conf
#       - mountPath: "/etcd0.etcd"
#         name: etcd0-storage
    ports:
    - containerPort: 1323
      name: client
      protocol: TCP
  volumes:
    - name: astrolabe-pes
      configMap:
        name: astrolabe-pes
    - name: astrolabe-conf
      configMap:
        name: astrolabe-conf
  imagePullSecrets:
  - name: regcred
  restartPolicy: Always
