apiVersion: v1
kind: Service
metadata:
  name: astrolabe-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: astrolabe-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 1323
      name: astrolabe
    - protocol: TCP
      port: 9090
      targetPort: 9000
      name: astrolabe-minio
