FROM ubuntu:21.04
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates 
RUN apt-get install -y curl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl
COPY bin/minio /bin
COPY overrides /
ENV LD_LIBRARY_PATH=/usr/local/vmware-vix-disklib-distrib/lib64
ENV MINIO_ACCESS_KEY=accesskey 
ENV MINIO_SECRET_KEY=secretkey 

ENTRYPOINT ["/bin/minio", "gateway", "astrolabe", "/etc/astrolabe_conf"]
