FROM ubuntu:latest
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates 
RUN apt-get install -y curl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl
COPY bin/astrolabe_server /bin
COPY overrides /
ENV LD_LIBRARY_PATH=/usr/local/vmware-vix-disklib-distrib/lib64

ENTRYPOINT ["/bin/astrolabe_server", "--confDir", "/etc/astrolabe_conf", "--insecure"]
#ENTRYPOINT ["/bin/bash"]
